

----cAU 1 :TẠO DATABASE VÀ INSERT DU LIEU
use master
go

if exists(select *from sysdatabases where name='QL_LOPHOC')
drop database QL_LOPHOC
go



CREATE DATABASE QL_LOPHOC
ON PRIMARY 
(
	Name=KS_primary,
	filename='E:\KT_KT_SQL\GD_02\KS_primary.mdf',
	size=5MB,
	maxsize=10MB,
	filegrowth=10%	
),
(
	Name=KS_second1_1,
	filename='E:\KT_KT_SQL\GD_02\KS_second1_1.ndf',
	size=3MB,
	maxsize=5MB,
	filegrowth=10%	
),
(
	Name=KS_second1_2,
	filename='E:\KT_KT_SQL\GD_02\KS_second1_2.ndf',
	size=3MB,
	maxsize=5MB,
	filegrowth=10%	
),
(
	Name=KS_second1_3,
	filename='E:\KT_KT_SQL\GD_02\KS_second1_3.ndf',
	size=3MB,
	maxsize=5MB,
	filegrowth=10%	
)
log on
(
	Name=KS_log,
	filename='E:\KT_KT_SQL\GD_02\KS_log.ldf',
	size=1MB,
	maxsize=5MB,
	filegrowth=15%	
)
go

USE QL_LOPHOC
GO

CREATE TABLE LOP(

MALOP CHAR(10) PRIMARY KEY,
TENLOP NVARCHAR(50),
HOCPHI INT,
NGAYBD DATE
)
GO

CREATE TABLE HOCVIEN(
MAHV CHAR(10) PRIMARY KEY,
HOTEN NVARCHAR(50),
PHAI NVARCHAR(5),
SOLOP_DK INT
)
GO

CREATE TABLE DANGKY(
MAHV CHAR(10),
MALOP CHAR(10),
NGAYDK DATE,
CONSTRAINT PK_DK PRIMARY KEY(MAHV,MALOP),
CONSTRAINT FK_DK_HV FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV),
CONSTRAINT FK_DK_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
)
GO

SET DATEFORMAT DMY
INSERT INTO LOP VALUES('ML01','10DHTH1',12000,'12/1/2020');
INSERT INTO LOP VALUES('ML02','10DHTH2',15000,'10/3/2020');
INSERT INTO LOP VALUES('ML03','10DHTH3',18000,'1/2/2020');

INSERT INTO HOCVIEN VALUES('HV01',N'VO THI THU HA',N'NỮ',4);
INSERT INTO HOCVIEN VALUES('HV02',N'DUONG DUY HA',N'NAM',5);
INSERT INTO HOCVIEN VALUES('HV03',N'VO KIM CHI',N'NỮ',3);

SET DATEFORMAT DMY
INSERT INTO DANGKY VALUES('HV01','ML01','12/1/2020');
INSERT INTO DANGKY VALUES('HV03','ML03','1/8/2020');
INSERT INTO DANGKY VALUES('HV02','ML03','15/3/2020');
go
-----CÂU 2:VIẾT THỦ TỤC:
--A.TRUYỀN VÀO MÃ LỚP ,TRẢ VỀ TÊN LỚP,THANG BẮT ĐẦU VÀ SỐ LƯƠNNG HỌC VIÊN ĐĂNG KÝ LỚP ĐÓ.
---vIẾT LỆNH GỌI THỰC THI THỦ TỤC.
CREATE PROC PS_CAUA (@MALOP CHAR(10))
AS
	BEGIN
	SELECT L.TENLOP,L.NGAYBD,HV.SOLOP_DK 
	FROM LOP L ,HOCVIEN HV,DANGKY DK
	WHERE L.MALOP=@MALOP AND L.MALOP=DK.MALOP AND HV.MAHV=DK.MAHV
	END
GO
------GOI THU THI
EXEC PS_CAUA 'ML03'
--XOA PROC
DROP PROC PS_CAUA

SELECT*FROM HOCVIEN
SELECT*FROM LOP
SELECT*FROM DANGKY
---B.VIẾT LỆNH THÊM CỘT TIỀN GIẢM VÀO BẢNG LOP .SỬ DỤNG CỦO ĐỂ CẬP NHẬT TIỀN GIẢM DỰA  DỰA VÀO NGÀY BẮT ĐẦU NHƯ SAU :
---NẾU LỚP BẮT ĐẦU TỪ THÁNG 9 NẮM 2021 TRỞ ĐI THÌ GIẢM 10% HỌC PHÍ ,ÁC TRƯỜNG HỢP KHÁC KHÔNG GIẢM (TIỀN GIẢM =0).
---NẾU
ALTER TABLE LOP
  ADD TIENGIAM FLOAT;
  SELECT * FROM LOP

Declare CAU2_B cursor
for select NGAYBD from LOP
open CAU2_B
declare @NGAYBD DATETIME
FETCH NEXT FROM CAU2_B INTO @NGAYBD
WHILE (@@FETCH_STATUS=0)
BEGIN 
	IF(YEAR(@NGAYBD)>=2021 AND MONTH(@NGAYBD)>=9)
	UPDATE LOP
	SET TIENGIAM= 0.1
	ELSE
	UPDATE LOP
	SET TIENGIAM= 0
	FETCH NEXT FROM CAU2_B INTO @NGAYBD
END
CLOSE CAU2_B
DEALLOCATE CAU2_B
SELECT * FROM LOP

--CÂU 3:SAO LƯU:
--A.

--B.

--CÂU 4:PHÂN QUYỀN:
--A.tạo nhóm quyền đặt tê phù hợp với thực tế.Mỗi nhóm quyền có 2 người dùng 
---tao dag nhap
sp_addlogin 'nhanvien1','2001190509'
go
sp_addlogin 'khachhang1','2001190508'
go
--tao nguoi dung
sp_adduser 'nhanvien1','nhanvien1'
go
sp_adduser 'khachhang1','khachhang1'
go
---tao quye
sp_addrole 'NHANVIEN'
go
sp_addrole 'KHAHHANG'
go

---them nguoi dung vao nhom quyen
sp_droprolemember 'NHANVIEN','nhanvien1'
go
sp_droprolemember 'KHAHHANG','khachhang1'
go

--B.cấp quyền
grant select
on LOP
to NHANVIEN
go
  

grant select,INSERT,UPDATE 
on HOCVIEN
to KHAHHANG
go

--C.HỤP CÁC THAO TÁC BỎ VÀO ỬOD VÀ GIẢI THÍCH RÕ RÀNG HỢP LÝ,

---CÂU 5:GIAO TÁC 
--A.TẠO 1 GIAO TÁC VỚI MỨC ĐỘ CÔ LẬP LÀ REPEATABLE READ , THƯJ THIỆN 2 HÀNH ĐỘNG:
--THÊM 1 ĐĂNG KÝ VÀO BẢNG DANGKY VOI GIA TRI ('HV003','L02','12/04/2021')
--CAP NHAT SO LOP DANGKY (SOLOP_DK) CỦA LỚP HỌC VIÊN TƯƠNG ỨNG TRÊN BẢNG HOCVIEN.
---P1:
BEGIN TRAN
	SET TRANSACTION ISOLATION
	LEVEL REPEATABLE READ
	INSERT INTO DANGKY
	VALUES ('HV003','L02','12/04/2021')

	WAITFOR DELAY '00:00:10'

	INSERT INTO DANGKY
	VALUES ('HV003','L02','12/04/2021')

COMMIT TRAN
GO

--P2:
BEGIN TRAN
	SET TRANSACTION ISOLATION
	LEVEL REPEATABLE READ
	UPDATE HOCVIEN
	SET SOLOP_DK=(SELECT COUNT(MALOP) FROM DANGKY WHERE MAHV='HV003')
	WHERE MAHV='HV003'

COMMIT TRAN

--B.CHUP HINH ACH HOAT DONG VÀ GIẢI THÍCH 
